"""The committed doc samples still parse, still carry the contract, and still
match the docs they are spliced into.

``docs/samples/`` is generated by ``scripts/render_readme_samples.py`` and
spliced into ``README.md`` and ``docs/commands.md`` between marker comments.
These tests hold three things about that (jwulff/fantasy-sports#93):

* every JSON sample is a valid envelope — it parses, carries
  ``"schema": "fantasy-sports/v1"``, and has every top-level key the contract
  promises;
* every error sample names a code the taxonomy defines, with that code's own
  exit status, and every code in the taxonomy has at least one sample;
* the docs are byte-identical to what splicing the committed samples produces,
  so a sample edited by hand or a doc edited inside a marker block fails here
  rather than silently drifting;
* every sample that can be produced offline is regenerated here and compared
  to its committed copy, timestamps aside, so a change to what a command
  renders fails CI until the samples are regenerated. The replayed and
  synthetic samples come from their own fixtures; the live ones are replayed
  from the committed canary recording of the same public league. The six
  the index marks ``offline: false`` — ``--help``, the pipe, ``doctor``, the
  two ``kona_player_info`` reads, and the 2019 probe — depend on the machine
  or on a request the recording never captured, and are held by the envelope
  tests only.

Offline. The script is imported (the repo root is on ``sys.path`` via
``pythonpath``); the regeneration runs commands in-process against a private
XDG tree and the unit tests' transport stub, and ``pytest-socket`` guarantees
nothing reaches the network.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from _harness import RecordedEspn  # noqa: E402

from fantasy_sports.core.errors import ErrorCode
from fantasy_sports.output import EXIT_CODES, SCHEMA, Envelope
from scripts.render_readme_samples import (
    DOCS,
    ELLIPSIS,
    INDEX_FILE,
    SAMPLES_DIR,
    Recorder,
    Sandbox,
    live_samples,
    load_index,
    referenced_names,
    replayed_samples,
    splice,
    synthetic_samples,
    trim,
)

#: The only leagues whose output may be committed (docs/testing.md §6).
COMMITTABLE_LEAGUES = {"1234", "99"}

ENVELOPE_KEYS = set(Envelope.success(provider="espn", data={}).to_dict())

INDEX = load_index()
JSON_SAMPLES = sorted(name for name, entry in INDEX.items() if entry["format"] == "json")
ERROR_SAMPLES = sorted(name for name, entry in INDEX.items() if entry["stream"] == "stderr")


def _read(name: str) -> str:
    return (SAMPLES_DIR / INDEX[name]["file"]).read_text(encoding="utf-8")


def _payload(name: str) -> dict:
    return json.loads(_read(name))


# --------------------------------------------------------------------------- #
# The index and the files agree
# --------------------------------------------------------------------------- #


def test_every_sample_file_is_indexed_and_every_index_entry_has_a_file():
    on_disk = {p.name for p in SAMPLES_DIR.iterdir() if p.name != INDEX_FILE.name}
    indexed = {entry["file"] for entry in INDEX.values()}
    assert on_disk == indexed


def test_the_generator_checks_against_the_real_schema_string():
    from scripts.render_readme_samples import SCHEMA as GENERATOR_SCHEMA

    assert GENERATOR_SCHEMA == SCHEMA


def test_every_sample_names_its_source_and_league():
    for name, entry in INDEX.items():
        assert entry["source"] in {"live", "replayed", "synthetic"}, name
        assert entry["league"], name
        assert entry["command"].startswith("fantasy-sports"), name


# --------------------------------------------------------------------------- #
# Every JSON sample is an envelope
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", JSON_SAMPLES)
def test_json_sample_is_a_complete_versioned_envelope(name: str):
    payload = _payload(name)
    assert payload["schema"] == SCHEMA
    assert set(payload) == ENVELOPE_KEYS, f"{name}: top-level keys drifted"
    # Exactly one of data / error, as the contract promises.
    assert (payload["data"] is None) != (payload["error"] is None)


@pytest.mark.parametrize("name", JSON_SAMPLES)
def test_json_sample_comes_from_a_committable_league(name: str):
    payload = _payload(name)
    assert payload["league_id"] in COMMITTABLE_LEAGUES | {None}, name


@pytest.mark.parametrize("name", JSON_SAMPLES)
def test_a_success_sample_exits_zero_on_stdout_and_a_failure_does_not(name: str):
    payload, entry = _payload(name), INDEX[name]
    if payload["error"] is None:
        assert entry["exit"] == 0 and entry["stream"] == "stdout"
    else:
        assert entry["exit"] != 0 and entry["stream"] == "stderr"


# --------------------------------------------------------------------------- #
# Every error sample is in the taxonomy, and the taxonomy is fully sampled
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", [n for n in ERROR_SAMPLES if INDEX[n]["format"] == "json"])
def test_error_sample_carries_a_taxonomy_code_and_its_exit_status(name: str):
    error = _payload(name)["error"]
    code = ErrorCode(error["code"])  # raises ValueError for anything outside the taxonomy
    assert INDEX[name]["exit"] == EXIT_CODES[code]
    assert set(error) == {
        "code",
        "message",
        "retryable",
        "agent_action",
        "remediation",
        "details",
        "health",
    }


def test_every_taxonomy_code_has_at_least_one_sample():
    sampled = {_payload(n)["error"]["code"] for n in ERROR_SAMPLES if INDEX[n]["format"] == "json"}
    assert sampled == {code.value for code in ErrorCode}


def test_usage_errors_are_sampled_as_prose_with_exit_two():
    usage = [n for n in ERROR_SAMPLES if INDEX[n]["format"] == "text"]
    assert usage, "no usage-error sample"
    for name in usage:
        assert INDEX[name]["exit"] == 2
        assert "Usage: fantasy-sports" in _read(name)


# --------------------------------------------------------------------------- #
# Nothing private, nothing secret
# --------------------------------------------------------------------------- #

_LEAGUE_IN_URL = re.compile(r"/leagues/(\d+)")


def test_no_sample_names_a_league_outside_the_committable_set():
    for name in INDEX:
        for found in _LEAGUE_IN_URL.findall(_read(name)):
            assert found in COMMITTABLE_LEAGUES, f"{name} names league {found}"


def test_no_sample_carries_a_cookie_value():
    """The placeholders the generator sets must not be echoed anywhere either."""
    for name in INDEX:
        text = _read(name)
        assert "placeholder-not-a-real-cookie" not in text, name
        assert "espn_s2=" not in text.lower(), name


# --------------------------------------------------------------------------- #
# The docs match the samples
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("doc", DOCS, ids=lambda p: p.name)
def test_doc_is_in_sync_with_its_samples(doc: Path):
    text = doc.read_text(encoding="utf-8")
    assert splice(text, INDEX, SAMPLES_DIR) == text, (
        f"{doc.name} drifted from docs/samples; run scripts/render_readme_samples.py"
    )


def test_every_sample_is_referenced_by_a_doc_and_every_reference_resolves():
    referenced: set[str] = set()
    for doc in DOCS:
        referenced |= referenced_names(doc.read_text(encoding="utf-8"))
    assert referenced == set(INDEX)


def test_the_command_reference_covers_every_registered_command():
    from fantasy_sports.commands import REGISTRY

    reference = (DOCS[1]).read_text(encoding="utf-8")
    for invocation in REGISTRY:
        assert f"### `{invocation}`" in reference, f"{invocation!r} has no section"


# --------------------------------------------------------------------------- #
# The offline samples still match what the code renders today
# --------------------------------------------------------------------------- #

#: Keys whose values legitimately differ between two generations of the same
#: sample: clocks, ages, and whether a fetch happened to hit the cache.
VOLATILE_KEYS = frozenset(
    {
        "generated_at",
        "data_as_of",
        "data_age_seconds",
        "fetched_at",
        "age_seconds",
        "cached",
        "stored_at",
        "age_days",
    }
)


def _stable(value):
    if isinstance(value, dict):
        return {k: _stable(v) for k, v in value.items() if k not in VOLATILE_KEYS}
    if isinstance(value, list):
        return [_stable(v) for v in value]
    return value


_TIMESTAMP = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z")
_AGE = re.compile(r"\b\d+s( \(cached\))?")


def _stable_text(text: str) -> str:
    """A table's header and sources lines carry the same volatile values."""
    return _AGE.sub("Ns", _TIMESTAMP.sub("T", text))


@pytest.fixture(scope="module")
def regenerated(tmp_path_factory: pytest.TempPathFactory) -> dict[str, str]:
    """Every offline-capable sample, produced fresh by the generator's own code.

    ``requests.get`` is pointed at the canary recording for the live block —
    the same league the docs were generated from, served from disk — and the
    replayed block installs its own stub. The Keychain backend is the null one
    so a developer's real cookies are never consulted.
    """
    import os

    import requests

    saved = {k: os.environ.get(k) for k in ("PYTHON_KEYRING_BACKEND",)}
    original_get = requests.get
    os.environ["PYTHON_KEYRING_BACKEND"] = "keyring.backends.null.Keyring"
    requests.get = RecordedEspn("espn/canary_2018.yaml")
    try:
        recorder = Recorder(Sandbox(tmp_path_factory.mktemp("samples")), offline_only=True)
        live_samples(recorder)
        replayed_samples(recorder)
        synthetic_samples(recorder)
    finally:
        requests.get = original_get
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
    return {sample.name: sample.text for sample in recorder.samples}


OFFLINE_SAMPLES = sorted(n for n, e in INDEX.items() if e["offline"])


def test_the_regeneration_covers_every_offline_sample_and_only_those(regenerated):
    assert set(regenerated) == set(OFFLINE_SAMPLES)


def test_only_the_six_environment_dependent_samples_are_exempt():
    exempt = {n for n, e in INDEX.items() if not e["offline"]}
    assert exempt == {"help", "pipe", "doctor", "raw.unfiltered", "raw.filter", "option-season"}


@pytest.mark.parametrize("name", OFFLINE_SAMPLES)
def test_offline_sample_matches_what_the_code_renders_today(name: str, regenerated):
    fresh, committed = regenerated[name], _read(name)
    if INDEX[name]["format"] == "json":
        assert _stable(json.loads(fresh)) == _stable(json.loads(committed)), (
            f"{name} drifted from the code; run scripts/render_readme_samples.py"
        )
    else:
        assert _stable_text(fresh) == _stable_text(committed), (
            f"{name} drifted from the code; run scripts/render_readme_samples.py"
        )


# --------------------------------------------------------------------------- #
# The trimmer keeps the shape it is trusted to keep
# --------------------------------------------------------------------------- #


def test_trim_keeps_every_top_level_key_and_marks_every_cut():
    envelope = Envelope.success(
        provider="espn",
        league_id="1234",
        season=2018,
        data=[{"name": f"t{i}", "raw": {k: k for k in "abcdefg"}} for i in range(5)],
        untrusted={f"[{i}].name": f"t{i}" for i in range(5)},
    ).to_dict()
    shorter = trim(envelope, items=2, raw_keys=3)
    assert set(shorter) == set(envelope)
    assert len(shorter["data"]) == 3 and shorter["data"][-1] == f"{ELLIPSIS} 3 more items"
    assert shorter["data"][0]["raw"][ELLIPSIS] == f"{ELLIPSIS} 4 more keys"
    assert shorter["untrusted"][ELLIPSIS] == f"{ELLIPSIS} 3 more entries"
    json.dumps(shorter)  # still serialisable


def test_trim_is_a_no_op_on_a_short_envelope():
    envelope = Envelope.success(provider="espn", data=[{"name": "x", "raw": {"a": 1}}]).to_dict()
    assert trim(envelope) == envelope
